// Generated by scripts/generate-agent-docs.mjs. Edit docs/agent sources, not this output.
export const agentToolHelp = {
  simulation_source:
    "List/create/read/discard native source workspaces. Use simulation_folder for saved experiments; simulation_edit for atomic code changes. Requests and revisions match simulation_files.",
  simulation_edit:
    "Atomically write or patch native source files. For project-folder, returned source.revision is Project.structureRevision: pass it directly to the next update.expectedRevision or simulation_run prepare.source.expectedStructureRevision. No reread after success. Reuses simulation_files validation and commit path.",
  simulation_data:
    "Sync/download complete registered files to the local workspace; artifact without outputPath is only a preview. analysisIndex + roles:[table] selects CSV; fileIds:[] syncs directory only. Reuse downloaded data. Find files with simulation_results catalog.",
  simulation_plot:
    "Generate editable local Python/config for registered results using panels or presets. This does not execute Python; check matplotlib once, then run locally. Existing plot files are not overwritten. Complex panel fields: describe_tool with this tool and a field path.",
  simulation_results:
    "Discover run history, evidence usage and catalogs; delete an exact completed run with dry-run and saved-result protection, or retry evidence export without rerunning. Use simulation_data for complete files. Receipts never inline samples.",
  simulation_run:
    "Normally submit run with a revisioned source; preparation is internal. For project-folder use the latest simulation_edit source.revision as expectedStructureRevision. Optional prepare/start supports inspection or frozen-input reuse. run/start/read accept waitMs 0–20000; resume via read with the same runId. One hosted slot. Retry uncertain submissions with the same requestId and payload. Results summarize collection and diagnostics; files are registered separately.",
  simulation_batch:
    "Prepare explicit batches or sweeps, then start/read/cancel the same batch. Uses the existing serialized executor and original request/revision checks. Use simulation_results for registered results and simulation_data for local files.",
  circuit_place:
    "Place built-in symbols, child Cells or existing instances and add power rails. actions is one atomic batch; obtain symbol IDs and resolved pins from catalog/inspect. Same planner and permissions as apply_actions.",
  circuit_wire:
    "Connect/disconnect in an atomic batch; via gives interior points. Explicit instance IDs avoid a full-Snapshot name lookup; server routing/validation is unchanged. Artwork contact is not connectivity.",
  circuit_transform:
    "Move/rotate/mirror individual targets, arrange or detach-move instances using one supported action batch. Preserves original planner boundaries and topology semantics. For mixed action families use apply_actions.",
  circuit_selection:
    "Translate/rotate/mirror/copy/align a selection. Uses original selection IDs, topology rules and atomic planner. For individual targets use circuit_transform; for mixed families use apply_actions.",
  circuit_text:
    "Add/edit labels and annotations, or move their anchors, through the original atomic action planner. Plain text is accepted where declared; exact rich text or unfamiliar fields are available from describe_tool by operation/field. Binding semantics stay unchanged.",
  circuit_properties:
    "Set device references, parameters, models and display flags with the original action planner. Keep physical units such as 10u. Model bindings and bulk semantics are unchanged. Mixed action families remain available through apply_actions.",
  describe_tool:
    "Offline exact contracts from the same tool registry. Omit selectors for a lightweight directory. tool + operations selects one or several action/operation branches with their call envelope; field queries an argument JSON Pointer (* for array items). editKind reads a canonical low-level edit, not a high-level action. Reuse contracts within the same version; never a prerequisite or permission gate.",
  connect:
    "Pair with the live browser editor. Pass its claim code once; later MCP processes can omit it and resume the saved, revocable connector. After connecting, read analog-canvas://reference/quickstart. Resource reads use the host's registered server alias (normally analog-canvas), not the normalized tool prefix analog_canvas. If unknown, discover the alias from the host resource list.",
  disconnect:
    "Revoke the current browser Agent session and erase this MCP host's saved connector. A fresh editor claim code is required afterwards.",
  connection_status:
    "Report runtime version, API origin and session observations. refresh:false is local-only. Attached means a browser socket exists, not verified execution readiness; unknown means the relay was not checked successfully.",
  project_cells:
    "Cloud Cell discovery/import; workspace list/bind-workspace/activate/open/save/copy. Bind an open workspace to work without selecting the human's tab; open supports background:true. Live tabs include unsaved work; Cloud reads saved versions. Copy reuses GUI transactions and dependencies. Details: analog-canvas://reference/mcp-tools.",
  gallery_circuits:
    "Page through every public Gallery circuit, then read one or up to 12 entries' complete Project Code and generated SPICE/Spectre netlist. Follow nextCursor until null and any remainingEntryIds until empty; pass netlistFormat:null when only Project Code is needed.",
  project_code:
    "Read or atomically replace the open Project's complete canonical Project Code. Replacement uses the live Project structure revision and the same validated, undoable commit path as the Editor's Project Code panel.",
  netlist_code:
    "Read the open Project's generated SPICE/Spectre netlist or replace its editable device names, models and values through the same planner as the Netlist panel. Use Project Code or structured circuit edits for topology and connectivity changes.",
  simulation:
    "Submit with run; prepare/start are optional. run/start/read accept waitMs 0–20000. Retry uncertain submissions with the same requestId; resume by runId. run.details has Specs/collection; catalog indexes full files. export retries saving, not execution. One slot.",
  simulation_files:
    "Compatibility entry for simulation_source, simulation_edit, simulation_data and simulation_plot. Edit with returned revisions; sync downloads complete files; prepare-plot writes editable local code and does not execute it. Details: analog-canvas://reference/mcp-simulation.",
  export_file:
    "Export Project or Canvas SVG/PNG/PDF to outputPath; Canvas requires documentId. For simulation data use simulation_files sync/download. simulation-plot returns SIMULATION_PLOT_RETIRED; use simulation_files prepare-plot.",
  import_file:
    "Stage local Project/SPICE files; inspect optionally selects documentId. import-cell commits one staged sourceDocumentId into targetDocumentId with mode replace-body or append, preserving the target interface and using existing edit scopes. Revisions are supplied when omitted. open opens a new Project tab; request-approval is for human-confirmed whole-Project replacement. No switch for import-cell.",
  get_context:
    "Read document identity/revision/counts with a lightweight request or clean cache. refresh:true reconciles external changes. Connect already returns context.",
  inspect:
    "Read document/objects/nets/traces/activity. pins (instanceIds), geometry (objectIds) and diagnostics use targeted server projections; full Document facts remain available.",
  search:
    "Case-insensitive search, including LaTeX, over one authorized document or scope:project. Results include documentId. Reuses clean Snapshots by default and loads authorized Project documents concurrently.",
  apply_actions:
    "Atomic high-level edits, Cell structure and history. circuit_* tools select common families. For unfamiliar fields use describe_tool operations:[kind]; no lookup prerequisite. detail:full includes removed diagnostic bodies.",
  advanced_transact:
    "Full transaction access: exactly one of edits, structureEdits, wireIntent, semanticIntent or command. Client supplies IDs/revisions; reconcile stale conflicts. Edit contracts are optional references.",
  verify:
    "Fresh Snapshot and diagnostic counts for milestones, not every edit. Optional expectedNetlist compares structural SPICE through the existing export; details adds bounded differences. Expressions/unsupported declarations are inconclusive, never electrical acceptance.",
  render:
    "Render the current document to SVG and return it as an image content block (image/svg+xml) plus a compact text summary (revision, sha256, byteLength).",
  simulation_folder:
    "Manage saved experiments. List is metadata-only. rootDocumentId binds a drawn Cell; dut generates a testbench with its exported name/port order. Edit native code with simulation_edit. refresh:true reconciles external changes.",
  simulation_output:
    "Legacy config v1 only: manage output ASTs. Native Code uses simulation_files for saves and postprocess Python; this tool cannot add parallel JSON rules. See analog-canvas://reference/mcp-simulation. Exact expression schema: analog-canvas://contract/tools/simulation_output.",
  simulation_measurement:
    "Legacy config v1 only: manage scalar measurement rules. Native VACASK uses authored Python and report_measurement; obtain helpers with simulation authoring-help. See analog-canvas://reference/mcp-simulation.",
  simulation_device_operating_point:
    "Legacy config v1 only: select terminal-derived MOS operating-point quantities. Native Code uses module-supported saves and native OP analysis; never guess i(pin). See analog-canvas://reference/mcp-simulation.",
};
export const agentServerInstructions =
  "Analog Canvas MCP adapter over the four-operation Agent API. Connect returns context; read analog-canvas://reference/quickstart and follow only the guidance for the current task. Inspect objects when needed. Do not guess symbol IDs, pin names, or revisions.";
