// Generated by scripts/generate-agent-docs.mjs. Edit docs/agent sources, not this output.
export const agentToolHelp = {
  connect:
    "Pair with the live browser editor. Pass its claim code once; later MCP processes can omit it and resume the saved, revocable connector. After connecting, read analog-canvas://reference/quickstart.",
  disconnect:
    "Revoke the current browser Agent session and erase this MCP host's saved connector. A fresh editor claim code is required afterwards.",
  connection_status:
    "Report runtime version, API origin and session observations. refresh:false is local-only. Attached means a browser socket exists, not verified execution readiness; unknown means the relay was not checked successfully.",
  project_cells:
    "List Cloud Projects, inspect reusable Cell interfaces, or atomically copy a Cell and its dependency closure into the open Project. No live cross-Project link. Requires account access; see analog-canvas://reference/mcp-tools.",
  simulation:
    "Prepare, start and read runs; export only when an artifact inventory is needed. Retain the SAME requestId and payload for an uncertain start retry. Native source editing remains available; authoring help is optional. Results: outputData.specs for verdicts, result.data for numbers; completion alone does not promise waveform capture. Use returned artifacts for full data when resultPreview is true. Device/vector mapping: analog-canvas://reference/mcp-simulation.",
  simulation_files:
    "Read/update simulation source or retrieve immutable artifacts. Owner is project-folder or session-workspace; updates require its current revision. Do not overwrite generated files. outputPath saves verified artifacts, not source. Ownership, patches and circuit-field mapping: analog-canvas://reference/mcp-simulation.",
  export_file:
    "Export the browser Project or Canvas SVG/PNG/PDF to an explicit local path. Canvas exports require documentId. Simulation results use returned run artifact references (or simulation export when an inventory is needed), then simulation_files artifact with outputPath to save raw/CSV/Spec files after digest verification. simulation-plot is retired and returns SIMULATION_PLOT_RETIRED; plot externally from raw/CSV.",
  import_file:
    "Stage a local Analog Canvas project or structural SPICE bundle, inspect/discard the candidate, or request browser approval. Staging never replaces the open project by itself.",
  get_context:
    "Compact context for one authorized document: identity, revision, instance/net counts, and error/warning totals. Refreshes by default so concurrent human edits are visible; set refresh:false only for a deliberate cached read.",
  inspect:
    "Read a document, object, net connectivity, diagnostics, or recent MCP activity. Refreshes by default; detail:full returns the document Snapshot with appearance, formulas, interfaces, and project definitions.",
  search:
    "Case-insensitive search, including LaTeX, over one authorized document or scope:project. Results include documentId. Refreshes by default.",
  apply_actions:
    "Apply one atomic batch, wire, GUI-planned command or focus operation. Helper previews edits and supplies revisions; split create/wire phases for resolved pins. Actions and native labels/displays: analog-canvas://reference/mcp-tools.",
  advanced_transact:
    "Submit exactly one of edits, structureEdits, wireIntent, semanticIntent or command. Helper previews and supplies revisions/IDs. Read analog-canvas://contract/edits/{kind} for one edit schema; full offline schema: analog-canvas://contract/advanced-edits. Reading is advisory.",
  verify:
    "Refresh the snapshot and report revision, error/warning totals, and which object IDs changed since the cached snapshot. Use after edits or when a transaction reported STATE_CHANGED.",
  render:
    "Render the current document to SVG and return it as an image content block (image/svg+xml) plus a compact text summary (revision, sha256, byteLength).",
  simulation_folder:
    "List/get/create/clone/rename/remove saved source experiments. rootDocumentId binds the drawn Cell; dut adds a text testbench using its exported name and ordered ports. Edit native source with simulation_files, not parallel JSON analyses. See analog-canvas://reference/mcp-simulation.",
  simulation_output:
    "Legacy config v1 only: manage output ASTs. Native Code uses simulation_files for saves and postprocess Python; this tool cannot add parallel JSON rules. See analog-canvas://reference/mcp-simulation.",
  simulation_measurement:
    "Legacy config v1 only: manage scalar measurement rules. Native VACASK uses authored Python and report_measurement; obtain helpers with simulation authoring-help. See analog-canvas://reference/mcp-simulation.",
  simulation_device_operating_point:
    "Legacy config v1 only: select terminal-derived MOS operating-point quantities. Native Code uses module-supported saves and native OP analysis; never guess i(pin). See analog-canvas://reference/mcp-simulation.",
};
export const agentServerInstructions =
  "Analog Canvas MCP adapter over the four-operation Agent API. Start with connect, read analog-canvas://reference/quickstart, then get_context. Read reference resources on demand; do not guess symbol IDs, pin names, or revisions.";
