const ROUND_PERIOD_TTF_BASE64 =
  "AAEAAAAKAIAAAwAgT1MvMkiLRg0AAAEoAAAAYGNtYXAADACBAAABkAAAADRnbHlm4Z5vWQAAAcwAAAAgaGVhZC3up0AAAACsAAAANmhoZWEFCgHYAAAA5AAAACRobXR4A8AAaQAAAYgAAAAIbG9jYQAQAAAAAAHEAAAABm1heHAABAAKAAABCAAAACBuYW1l3HZZJQAAAewAAAHacG9zdAAVAAAAAAPIAAAAJgABAAAAAQAAKn0opV8PPPUAAwPoAAAAAOa4MtEAAAAA5rgy0QBpABQA/wCqAAAAAwACAAAAAAAAAAEAAAOg/xQAAAJYAGkAaQD/AAEAAAAAAAAAAAAAAAAAAAACAAEAAAACAAgAAQAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAwHgAZAABQAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAPz8/PwAAAC4ALgOg/xQAAAOgAOwAAAAAAAAAAAIHAtkAAAAgAAACWAAAAWgAaQAAAAIAAAADAAAAFAADAAEAAAAUAAQAIAAAAAQABAABAAAALv//AAAALv///9MAAQAAAAAAAAAAABAAAAABAGkAFAD/AKoABwAANzI1NCMiFRS0S0tLFEtLS0sAAAAADACWAAEAAAAAAAEAEAAAAAEAAAAAAAIABwAQAAEAAAAAAAMAHAAXAAEAAAAAAAQAGAAzAAEAAAAAAAUACwBLAAEAAAAAAAYAFgBWAAMAAQQJAAEAIABsAAMAAQQJAAIADgCMAAMAAQQJAAMAOACaAAMAAQQJAAQAMADSAAMAAQQJAAUAFgECAAMAAQQJAAYALAEYSUNNIFJvdW5kIFBlcmlvZFJlZ3VsYXJJQ00gUm91bmQgUGVyaW9kIFJlZ3VsYXIgMS4wSUNNIFJvdW5kIFBlcmlvZCBSZWd1bGFyVmVyc2lvbiAxLjBJQ01Sb3VuZFBlcmlvZC1SZWd1bGFyAEkAQwBNACAAUgBvAHUAbgBkACAAUABlAHIAaQBvAGQAUgBlAGcAdQBsAGEAcgBJAEMATQAgAFIAbwB1AG4AZAAgAFAAZQByAGkAbwBkACAAUgBlAGcAdQBsAGEAcgAgADEALgAwAEkAQwBNACAAUgBvAHUAbgBkACAAUABlAHIAaQBvAGQAIABSAGUAZwB1AGwAYQByAFYAZQByAHMAaQBvAG4AIAAxAC4AMABJAEMATQBSAG8AdQBuAGQAUABlAHIAaQBvAGQALQBSAGUAZwB1AGwAYQByAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAEQAA";

/**
 * One self-authored U+002E glyph: a circular full stop with a 0.36 em
 * advance, matching the deterministic narrow-glyph metric. Every other code
 * point falls through to the calibrated schematic font stack. Keeping this a
 * font boundary preserves the canonical "." character, browser caret and
 * selection behavior, and SVG text semantics.
 */
const schematicRoundPeriodFontFamily = "ICM Round Period";

const roundPeriodSource = `url(data:font/ttf;base64,${ROUND_PERIOD_TTF_BASE64}) format("truetype")`;

export const schematicRoundPeriodFontFaceCss = [
  [400, "normal"],
  [400, "italic"],
  [700, "normal"],
  [700, "italic"],
]
  .map(
    ([weight, style]) =>
      `@font-face{font-family:"${schematicRoundPeriodFontFamily}";src:${roundPeriodSource};font-weight:${weight};font-style:${style};font-display:block;unicode-range:U+002E}`,
  )
  .join("");

export function withSchematicRoundPeriodFont(fallbackStack: string): string {
  return `'${schematicRoundPeriodFontFamily}',${fallbackStack}`;
}
